version: "3.8"

services:
  nexus:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:80"
    depends_on:
      pgsql:
        condition: service_healthy
    networks:
      - nexus-dev
  pgsql:
    image: postgres:alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: nexus
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - nexus-dev
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root", "-d", "nexus"]
      interval: 10s
      retries: 5

networks:
  nexus-dev:
