version: "3.8"

services:
  nexus:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:80"
    networks:
      - nexus-dev
  pgsql:
    image: postgres:alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: nexus
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - nexus-dev

networks:
  nexus-dev:
